(function () {
  const skinBasePath = "./assets/skins";

  window.DDZ_SKIN_CONFIGS = [
    {
      id: "sanguo",
      name: "三国暗金版",
      background: `${skinBasePath}/sanguo/backgrounds/battlefield.png`,
      cardBack: "",
      cardFacePath: `${skinBasePath}/sanguo/cards`,
      avatarFrame: `${skinBasePath}/sanguo/ui/avatar-frame.png`,
      chatPanel: "",
      chooseGlow: "",
      generatedAssets: {
        lobbyBg: "./public/assets/generated/lobby-bg.webp",
        modeTaoyuan: "./public/assets/generated/mode-taoyuan.webp",
        modeGuandu: "./public/assets/generated/mode-guandu.webp",
        modeChibi: "./public/assets/generated/mode-chibi.webp",
        modeQunxiong: "./public/assets/generated/mode-qunxiong.webp",
        aiPracticeGeneral: "./public/assets/generated/ai-practice-general.webp",
        friendBattleGeneral: "./public/assets/generated/friend-battle-general.webp",
        rank: "./public/assets/generated/rank.webp",
        record: "./public/assets/generated/record.webp",
        shop: "./public/assets/generated/shop.webp",
        task: "./public/assets/generated/task.webp",
        gift: "./public/assets/generated/gift.webp",
        settings: "./public/assets/generated/settings.webp",
      },
      avatars: {
        landlord: `${skinBasePath}/sanguo/avatars/landlord.jpg`,
        farmerA: `${skinBasePath}/sanguo/avatars/farmer-green.jpg`,
        farmerB: `${skinBasePath}/sanguo/avatars/farmer-red.jpg`,
      },
      assets: {
        cardFaces: false,
        cardBack: false,
        avatarFrame: true,
        avatars: true,
        chatPanel: false,
        chooseGlow: false,
      },
      buttonStyle: {
        radius: "16px",
        borderWidth: "1px",
        shadow: "0 14px 30px rgba(0, 0, 0, 0.46)",
        sprite: `${skinBasePath}/sanguo/ui/buttons.png`,
      },
      tableStyle: {
        texture: "",
        radius: "18px",
        borderWidth: "1px",
      },
      themeColors: {
        bgMain: "#090705",
        bgAccent: "#2a160c",
        panelBg: "rgba(20, 12, 8, 0.62)",
        panelBgStrong: "rgba(28, 16, 10, 0.82)",
        panelBorder: "rgba(239, 174, 82, 0.34)",
        primary: "#f0b45b",
        primarySoft: "rgba(240, 170, 72, 0.18)",
        gold: "#ffd384",
        warning: "#ffd36a",
        danger: "#d85845",
        textMain: "#fff0cc",
        textPanel: "#ffe5ad",
        textMuted: "#cfad7a",
        cardText: "#23150c",
        cardRed: "#a42725",
        cardBg: "#f7ecd7",
        cardBorder: "#b87934",
        glow: "rgba(255, 173, 64, 0.34)",
        shadow: "rgba(0, 0, 0, 0.58)",
      },
    },
    {
      id: "classic",
      name: "经典夜蓝版",
      background: "",
      cardBack: "",
      cardFacePath: `${skinBasePath}/classic/cards`,
      avatarFrame: "",
      chatPanel: "",
      chooseGlow: "",
      generatedAssets: {},
      avatars: {},
      assets: {
        cardFaces: false,
        cardBack: false,
        avatarFrame: false,
        avatars: false,
        chatPanel: false,
        chooseGlow: false,
      },
      buttonStyle: {
        radius: "8px",
        borderWidth: "1px",
        shadow: "0 8px 18px rgba(0, 0, 0, 0.18)",
        sprite: "",
      },
      tableStyle: {
        texture: "",
        radius: "18px",
        borderWidth: "1px",
      },
      themeColors: {
        bgMain: "#08131d",
        bgAccent: "#15283a",
        panelBg: "rgba(20, 33, 47, 0.72)",
        panelBgStrong: "rgba(31, 47, 65, 0.88)",
        panelBorder: "rgba(202, 151, 79, 0.34)",
        primary: "#d8a75d",
        primarySoft: "rgba(216, 167, 93, 0.12)",
        gold: "#f0c46f",
        warning: "#f0c46f",
        danger: "#c85a4b",
        textMain: "#f4ead6",
        textPanel: "#f4ead6",
        textMuted: "#b6a68e",
        cardText: "#22180f",
        cardRed: "#a72b2b",
        cardBg: "#f3ead8",
        cardBorder: "#c89a5a",
        glow: "rgba(216, 167, 93, 0.20)",
        shadow: "rgba(0, 0, 0, 0.48)",
      },
    },
  ];
})();
